jQuery(document).ready(function(){jQuery(".ask_classify_select").change(function(){jQuery("#filter_by_cat").trigger("click")});$("#answer").bind("click",function(){var a=jQuery("#answer_form").serialize();jQuery.ajax({type:"POST",beforeSend:function(){},url:window.location.href,processData:!0,data:a+"&rnd="+Math.random(),dataType:"json",success:function(a){var c=a.code;if(c==1){if(c=combine_login_page_params(a.params),confirm(a.msg))window.location.href="index.php?r=site/login"+c}else c==2?(show_tip_dialog("\u63d0\u793a",
a.msg),jQuery("#answers_list").load("index.php?r=qa/loadAnswers&id="+a.params.qid),jQuery("#answer_content").val(""),jQuery("#remaining_words_count").html(1E3).css({color:"green"})):c==3&&jQuery("#msg").html(a.msg)}});return!1});jQuery(".best_answer").bind("click",function(){var a=jQuery(this).parent(),b=a.serialize(),a=a.attr("action");jQuery.ajax({type:"POST",beforeSend:function(){},url:a,processData:!0,data:b+"&rnd="+Math.random(),dataType:"text",success:function(a){a==1&&window.location.reload()}})});
jQuery(".ding").bind("click",function(){var a=jQuery(this),b=a.parent(),c=b.serialize(),b=b.attr("action");jQuery.ajax({type:"POST",beforeSend:function(){},url:b,processData:!0,data:c+"&rnd="+Math.random(),dataType:"text",success:function(b){(b=parseInt(b))&&a.before("<span style='color:#FF4400;font-size:14px;padding-left:10px;'>\u9876("+b+")</span>").remove()}});return!1})});var Class={create:function(){return function(){this.initialize.apply(this,arguments)}}};
function extend(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.superclass=b.prototype;if(b.prototype.constructor==Object.prototype.constructor)b.prototype.constructor=b}function getPageSize(){var a=document.documentElement;return arrayPageSize=[window.innerWidth||self.innerWidth||a&&a.clientWidth||document.body.clientWidth,window.innerHeight||self.innerHeight||a&&a.clientHeight||document.body.clientHeight]}
function empty(a){if(a)if(a instanceof Array)return a.length==0;else if(a instanceof Object){for(var b in a)return!1;return!0}else return!a;else return!1}function contains(a,b){for(;!empty(b);)if(a==b)return!0;else if(b)b=b.parentNode,contains(a,b);else break;return!1}function values(a){if(hasArrayNature(a))throw new TypeError("values() was passed an array; use to_array().");var b=[],c;for(c in a)b.push(a[c]);return b}
function hasArrayNature(a){return!a||typeof a!="object"||!("length"in a)?!1:a instanceof Array||"callee"in a||"push"in a&&"pop"in a?!0:!1}function is_scalar(a){return/string|number|Boolean/.test(typeof a)}var ge=window.ge||function(a,b){var c;c="string"!=typeof a?a:document.getElementById(a);!b&&window.NodeAugment&&NodeAugment.extend(c);return c},basic={$:window.$||ge};
function bind(a,b){var c=Array.prototype.slice.call(arguments,2),d=function(){var d=a||(this==window?!1:this),f=c.concat(Array.prototype.slice.call(arguments));if(typeof b=="string"){if(d[b])return d[b].apply(d,f)}else return b.apply(d,f)};if(typeof b=="string")d.name=b;else if(b&&b.name)d.name=b.name;d.toString=function(){return bind._toString(a,c,b)};return d}bind._toString=bind._toString||function(a,b,c){return typeof c=="string"?"late bind<"+c+">":"bound<"+c.toString()+">"};
function rand32(){return Math.floor(Math.random()*4294967295)}function getTime(a){a==null&&(a=new Date);var b=a.getFullYear(),c=a.getMonth()+1,d=a.getDate(),e=a.getHours(),f=a.getMinutes(),g=a.getSeconds(),a=a.getTime()%1E3;b+="-";c<10&&(b+="0");b+=c+"-";d<10&&(b+="0");b+=d+" ";e<10&&(b+="0");b+=e+":";f<10&&(b+="0");b+=f+":";g<10&&(b+="0");b+=g;b+=" ";a<100&&(b+="0");a<10&&(b+="0");b+=a;return b}function hideMsgBox(a,b){if(a)return contains(document.getElementById(b),a.toElement)?!0:!1}
window.addEventListener&&FixPrototypeForGecko();function FixPrototypeForGecko(){HTMLElement.prototype.__defineGetter__("runtimeStyle",element_prototype_get_runtimeStyle);window.constructor.prototype.__defineGetter__("event",window_prototype_get_event);Event.prototype.__defineGetter__("srcElement",event_prototype_get_srcElement);Event.prototype.__defineGetter__("fromElement",element_prototype_get_fromElement);Event.prototype.__defineGetter__("toElement",element_prototype_get_toElement)}
function element_prototype_get_runtimeStyle(){return this.style}function window_prototype_get_event(){return SearchEvent()}function event_prototype_get_srcElement(){return this.target}function element_prototype_get_fromElement(){var a;if(this.type=="mouseover")a=this.relatedTarget;else if(this.type=="mouseout")a=this.target;if(a){for(;a.nodeType!=1;)a=a.parentNode;return a}}
function element_prototype_get_toElement(){var a;if(this.type=="mouseout")a=this.relatedTarget;else if(this.type=="mouseover")a=this.target;if(a){for(;a.nodeType!=1;)a=a.parentNode;return a}}function SearchEvent(){if(document.all)return window.event;for(func=SearchEvent.caller;func!=null;){var a=func.arguments[0];if(a instanceof Event)return a;func=func.caller}return null}
String.prototype.gblen=function(){for(var a=0,b=0;b<this.length;b++)this.charCodeAt(b)>=224?a+=3:this.charCodeAt(b)>=192?a+=2:(this.charCodeAt(b)>=65&&this.charCodeAt(b),a+=1);return a};
String.prototype.gbtrim=function(a,b){for(var c="",d=b||"",e=0,f=0;f<this.length;f++)this.charCodeAt(f)>=224?e+=3:this.charCodeAt(f)>=192?e+=2:(this.charCodeAt(f)>=65&&this.charCodeAt(f),e+=1);if(e<=a)return this;e=0;a=a>d.length?a-d.length:a;for(f=0;f<this.length;f++)this.charCodeAt(f)>127||this.charCodeAt(f)==94?e+=2:e++;e>a&&(c+=this.charAt(0),c+=d,c+=this.charAt(this.length-1));return c};String.prototype.trimn=function(){return this.replace(/[\r|\n]/g,"")};
String.prototype.ltrim=function(){return this.replace(/(^\s*)/g,"")};String.prototype.rtrim=function(){return this.replace(/(\s*$)/g,"")};Array.prototype.find_key=function(a){for(var b=this.length,c=0;c<b;c++)if(this[c].id==a)return c;return!1};Array.prototype.remove=function(a){for(var b=[],c=this.length,a=parseInt(a),d=0;d<c;d++)d!=a&&b.push(this[d]);return b};function strLeft(a,b){return a.slice(0,b)}
function htmlspecialchars(a){if(typeof a=="undefined"||a===null||!a.toString)return"";if(a===!1)return"0";else if(a===!0)return"1";return a.toString().replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#039;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function htmlize(a){return htmlspecialchars(a).replace(/\n/g,"<br />")}
function escape_js_quotes(a){return typeof a=="undefined"||!a.toString?"":a.toString().replace(/\\/g,"\\").replace(/\n/g,"\n").replace(/\r/g,"\r").replace(/"/g,'"').replace(/'/g,"'").replace(/</g,"<").replace(/>/g,">").replace(/&/g,"&")}
function chain(a,b){var c,d=[];for(c=0;c<arguments.length;c++)d.push(arguments[c]);c=function(a){for(var a=a||window.event,b=0;b<d.length;b++)if(d[b]&&d[b].apply(this,arguments)===!1)return!1;else if(a&&a.cancelBubble)break;return!0};c.toString=function(){return chain._toString(d)};return c}if(!chain._toString)chain._toString=function(a){var b="chained fns";a.filter();for(var c=0;c<a.length;c++)b+="\\n"+a[c].toString();return b};
function $N(a,b,c){if(typeof b!="object"||DOM.isNode(b)||b instanceof Array||b instanceof HTML)c=b,b=null;return DOM.create(a,b,c)}var $$=function(a){return DOM.scry.apply(null,[document].concat($A(arguments)))};function setCookie(a,b,c,d){if(c){var e=new Date;e.setTime((new Date).getTime()+c)}document.cookie=a+"="+encodeURIComponent(b)+"; "+(c?"expires="+e.toGMTString()+"; ":"")+"path="+(d||"/")+"; domain="+window.location.hostname.replace(/^.*(\.facebook\..*)$/i,"$1")}
function clearCookie(a){document.cookie=a+"=; expires=Sat, 01 Jan 2000 00:00:00 GMT; path=/; domain="+window.location.hostname.replace(/^.*(\.facebook\..*)$/i,"$1")}function getCookie(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return decodeURIComponent(d.substring(a.length,d.length))}return null}function arrayize(a){return!hasArrayNature(a)?[a]:a}
function copy_properties(a,b){var a=a||{},b=b||{},c;for(c in b)a[c]=b[c];if(b.hasOwnProperty&&b.hasOwnProperty("toString")&&typeof b.toString!="undefined"&&a.toString!==b.toString)a.toString=b.toString;return a}
var ua={ie:function(){return ua._populate()||this._ie},firefox:function(){return ua._populate()||this._firefox},opera:function(){return ua._populate()||this._opera},safari:function(){return ua._populate()||this._safari},safariPreWebkit:function(){return ua._populate()||this._safari<500},chrome:function(){return ua._populate()||this._chrome},windows:function(){return ua._populate()||this._windows},osx:function(){return ua._populate()||this._osx},linux:function(){return ua._populate()||this._linux},
iphone:function(){return ua._populate()||this._iphone},_populated:!1,_populate:function(){if(!ua._populated){ua._populated=!0;var a=/(?:MSIE.(\d+\.\d+))|(?:(?:Firefox|GranParadiso|Iceweasel).(\d+\.\d+))|(?:Opera(?:.+Version.|.)(\d+\.\d+))|(?:AppleWebKit.(\d+(?:\.\d+)?))/.exec(navigator.userAgent),b=/(Mac OS X)|(Windows)|(Linux)/.exec(navigator.userAgent),c=/\b(iPhone|iP[ao]d)/.exec(navigator.userAgent);if(a){ua._ie=a[1]?parseFloat(a[1]):NaN;if(ua._ie>=8&&!window.HTMLCollection)ua._ie=7;ua._firefox=
a[2]?parseFloat(a[2]):NaN;ua._opera=a[3]?parseFloat(a[3]):NaN;ua._safari=a[4]?parseFloat(a[4]):NaN;ua._safari?(a=/(?:Chrome\/(\d+\.\d+))/.exec(navigator.userAgent),ua._chrome=a&&a[1]?parseFloat(a[1]):NaN):ua._chrome=NaN}else ua._ie=ua._firefox=ua._opera=ua._chrome=ua._safari=NaN;b?(ua._osx=!!b[1],ua._windows=!!b[2],ua._linux=!!b[3]):ua._osx=ua._windows=ua._linux=!1;ua._iphone=c}}};
Function.prototype.bind=function(a){var b=[a,this].concat(Array.prototype.slice.call(arguments,1));return bind.apply(null,b)};
window.CSS=window.CSS||{hasClass:function(a,b){return(" "+basic.$(a,!0).className+" ").indexOf(" "+b+" ")>-1},addClass:function(a,b){a=basic.$(a,!0);if(b&&!CSS.hasClass(a,b))a.className=a.className?a.className+" "+b:b;return a},setOpacity:function(a,b){var a=basic.$(a),c=b==1;try{a.style.opacity=c?"":""+b}catch(d){}try{a.style.filter=c?"":"alpha(opacity="+b*100+")"}catch(e){}},getOpacity:function(a){var a=basic.$(a),b=CSS.getStyle(a,"filter"),c=null;return b&&(c=/(\d+(?:\.\d+)?)/.exec(b))?parseFloat(c.pop())/
100:(b=CSS.getStyle(a,"opacity"))?parseFloat(b):1},setStyle:function(a,b,c){a.style[b]=c;return a},getStyle:function(a,b){function c(a){return a.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}a=basic.$(a);if(window.getComputedStyle)return window.getComputedStyle(a,null).getPropertyValue(c(b));if(document.defaultView&&document.defaultView.getComputedStyle){var d=document.defaultView.getComputedStyle(a,null);if(d)return d.getPropertyValue(c(b));if(b=="display")return"none";Util.error("Can't retrieve requested style %q due to a bug in Safari",
b)}return a.currentStyle?a.currentStyle[b]:a.style[b]},removeClass:function(a,b){a=basic.$(a,!0);a.className=a.className.replace(RegExp("(^|\\s)"+b+"(?=\\s|$)","g")," ");return a},toggleClass:function(a,b){return(CSS.hasClass(a,b)?CSS.removeClass:CSS.addClass)(a,b)},setOpacity:function(a,b){var a=basic.$(a),c=b==1;try{a.style.opacity=c?"":""+b}catch(d){}try{a.style.filter=c?"":"alpha(opacity="+b*100+")"}catch(e){}},getOpacity:function(a){var a=basic.$(a),b=CSS.getStyle(a,"filter"),c=null;return b&&
(c=/(\d+(?:\.\d+)?)/.exec(b))?parseFloat(c.pop())/100:(b=CSS.getStyle(a,"opacity"))?parseFloat(b):1},setStyle:function(a,b,c){a.style[b]=c;return a},getStyle:function(a,b){function c(a){return a.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}a=basic.$(a);if(window.getComputedStyle)return window.getComputedStyle(a,null).getPropertyValue(c(b));if(document.defaultView&&document.defaultView.getComputedStyle){var d=document.defaultView.getComputedStyle(a,null);if(d)return d.getPropertyValue(c(b));
if(b=="display")return"none";Util.error("Can't retrieve requested style %q due to a bug in Safari",b)}return a.currentStyle?a.currentStyle[b]:a.style[b]}};function HTML(a){if(this===window)return a instanceof HTML?a:new HTML(a);this._content=a;this._defer=!1;this._extra_action="";this._nodes=null;this._inline_js=bagofholding;this._has_option_elements=!1;return this}
copy_properties(HTML.prototype,{toString:function(){var a=this._content;this._extra_action&&(a+='<script type="text/javascript">'+this._extra_action+"<\/script>");return a},setAction:function(a){this._extra_action=a;return this},getAction:function(){this._fillCache();var a=function(){this._inline_js();eval_global(this._extra_action)}.bind(this);return this.getDeferred()?a.defer.bind(a):a},setDeferred:function(a){this._defer=!!a;return this},getDeferred:function(){return this._defer},getContent:function(){return this._content},
getNodes:function(){this._fillCache();return this._nodes},getRootNode:function(){return this.getNodes()[0]},hasOptionElements:function(){this._fillCache();return this._has_option_elements},_fillCache:function(){if(null===this._nodes){var a=this._content;if(a){var a=a.replace(/(<(\w+)[^>]*?)\/>/g,function(a,b,c){return c.match(/^(abbr|br|col|img|input|link|meta|param|hr|area|embed)$/i)?a:b+"></"+c+">"}),b=a.trim().toLowerCase(),c=document.createElement("div"),d=!1,e=!b.indexOf("<opt")&&[1,'<select multiple="multiple" class="__WRAPPER">',
"</select>"]||!b.indexOf("<leg")&&[1,'<fieldset class="__WRAPPER">',"</fieldset>"]||b.match(/^<(thead|tbody|tfoot|colg|cap)/)&&[1,'<table class="__WRAPPER">',"</table>"]||!b.indexOf("<tr")&&[2,'<table><tbody class="__WRAPPER">',"</tbody></table>"]||(!b.indexOf("<td")||!b.indexOf("<th"))&&[3,'<table><tbody><tr class="__WRAPPER">',"</tr></tbody></table>"]||!b.indexOf("<col")&&[2,'<table><tbody></tbody><colgroup class="__WRAPPER">',"</colgroup></table>"]||null;if(null===e)c.className="__WRAPPER",ua.ie()?
(e=[0,'<span style="display:none">&nbsp;</span>',""],d=!0):e=[0,"",""];for(c.innerHTML=e[1]+a+e[2];e[0]--;)c=c.lastChild;d&&c.removeChild(c.firstChild);if(0!=c.getElementsByTagName("option").length)this._has_option_elements=!0;if(ua.ie()){a=!b.indexOf("<table")&&-1==b.indexOf("<tbody")?c.firstChild&&c.firstChild.childNodes:e[1]=="<table>"&&-1==b.indexOf("<tbody")?c.childNodes:[];for(b=a.length-1;b>=0;--b)a[b].nodeName&&a[b].nodeName.toLowerCase()=="tbody"&&a[b].childNodes.length==0&&a[b].parentNode.removeChild(a[b])}for(var a=
c.getElementsByTagName("script"),f=[],b=0;b<a.length;b++)a[b].src?f.push(Bootloader.requestResource.bind(Bootloader,"js",a[b].src)):f.push(eval_global.bind(null,a[b].innerHTML));for(b=a.length-1;b>=0;b--)a[b].parentNode.removeChild(a[b]);this._nodes=to_array(c.childNodes);this._inline_js=function(){for(var a=0;a<f.length;a++)f[a]()}}else this._nodes=[]}}});
var DOM={find:function(a,b){var c=DOM.scry(a,b);return 1!=c.length?null:c[0]},scry:function(a,b,c){for(var b=b.split(" "),d=[a||document],a=0;a<b.length;a++){if(d.length==0)break;if(b[a]!=""){var e=b[a],f=[],g=!1;if(e.charAt(0)=="^")if(a==0)g=!0,e=e.slice(1);else return;var e=e.replace(/\./g," ."),e=e.replace(/\#/g," #"),e=e.replace(/\[/g," ["),e=e.split(" "),h=e[0]||"*";if(e[1]&&e[1].charAt(0)=="#"){if((e=ge(e[1].slice(1),!0))&&("*"==h||e.tagName.toLowerCase()==h))for(var k=0;k<d.length;k++)if(g&&
DOM.contains(e,d[k])){f=[e];break}else if(document==d[k]||DOM.contains(d[k],e)){f=[e];break}}else{for(var k=[],j=d.length,i=0;i<j;i++){if(g)for(var l=[],m=d[i].parentNode,n=h=="*";DOM.isNode(m,DOM.NODE_TYPES.ELEMENT);)(n||m.tagName.toLowerCase()==h)&&l.push(m),m=m.parentNode;else l=d[i].getElementsByTagName(h);m=l.length;for(n=0;n<m;n++)k.push(l[n])}for(var o,h=1;h<e.length;h++){j=e[h];j.charAt(0)=="."?(d=!0,o=RegExp("\\b"+j.substring(1)+"\\b")):d=!1;for(i=0;i<k.length;i++)if(l=k[i])d?o.test(l.className)||
delete k[i]:(m=j.slice(1,j.length-1),m.indexOf("=")==-1?l.getAttribute(m)===null&&delete k[i]:(n=m.split("="),m=n[0],n=n[1],n=n.slice(1,n.length-1),l.getAttribute(m)!=n&&delete k[i]))}for(i=0;i<k.length;i++)if(k[i]&&(f.push(k[i]),g))break}d=f}}if(!c)for(a=0;a<d.length;a++)d[a]=basic.$(d[a]);return d},getText:function(){var a=document.createElement("div").innerText==null?"textContent":"innerText";return function(b){return b?DOM.isNode(b,DOM.NODE_TYPES.TEXT)?b.data:b[a]:""}}(),getSelection:function(){var a=
window.getSelection,b=document.selection;if(a)return a()+"";else if(b)return b.createRange().text;return null},create:function(a,b,c,d){a=document.createElement(a);if(b){b=copy_properties({},b);b.style&&(copy_properties(a.style,b.style),delete b.style);for(var e in b)e.toLowerCase().indexOf("on")==0&&(typeof b[e]=="function"&&(window.Event&&Event.listen?Event.listen(a,e.substr(2),b[e]):a[e]=b[e]),delete b[e]);copy_properties(a,b)}c!=void 0&&DOM.setContent(a,c);return basic.$(a,d)},prependContent:function(a,
b){if(!DOM.isNode(a))throw Error("DOM.prependContent: reference element is not a node");return DOM._addContent(b,function(b){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},a)},insertAfter:function(a,b){if(!DOM.isNode(a)||!a.parentNode)throw Error("DOM.insertAfter: reference element is not a node");return DOM._addContent(b,function(b){a.nextSibling?a.parentNode.insertBefore(b,a.nextSibling):a.parentNode.appendChild(b)},a.parentNode)},insertBefore:function(a,b){if(!DOM.isNode(b)||!b.parentNode)throw Error("DOM.insertBefore: reference element is not a node or does not have a parent.");
return DOM._addContent(a,function(a){b.parentNode.insertBefore(a,b)},b.parentNode)},setContent:function(a,b){if(!DOM.isNode(a))throw Error("DOM.setContent: reference element is not a node");DOM.empty(a);return DOM.appendContent(a,b)},appendContent:function(a,b){if(!DOM.isNode(a))throw Error("DOM.appendContent: reference element is not a node");return DOM._addContent(b,function(b){a.appendChild(b)},a)},replace:function(a,b){if(!DOM.isNode(a)||!a.parentNode)throw Error("DOM.replace: reference element must be a node with a parent");
return DOM._addContent(b,function(b){a.parentNode.replaceChild(b,a)},a.parentNode)},remove:function(a){a=basic.$(a,!0);a.parentNode&&a.parentNode.removeChild(a)},empty:function(a){for(a=basic.$(a,!0);a.firstChild;)DOM.remove(a.firstChild)},contains:function(a,b){a=ge(a,!0);b=ge(b,!0);return!a||!b?!1:a===b?!0:DOM.isNode(a,"#text")?!1:DOM.isNode(b,"#text")?DOM.contains(a,b.parentNode):a.contains?a.contains(b):a.compareDocumentPosition?!!(a.compareDocumentPosition(b)&16):!1},getRootElement:function(){var a=
null;window.Quickling&&Quickling.isActive()&&(a=ge("content"));return a||document.body},isNode:function(a,b){typeof Node=="undefined"&&(Node=null);try{if(!a||!(Node!=void 0&&a instanceof Node||a.nodeName))return!1}catch(c){return!1}if(typeof b!=="undefined"){var d,e;try{d=(new String(a.nodeName)).toUpperCase(),e=a.nodeType}catch(f){return!1}for(var g=0;g<b.length;g++)try{if(d==b[g]||e==b[g])return!0}catch(h){}return!1}return!0},NODE_TYPES:{ELEMENT:1,ATTRIBUTE:2,TEXT:3,CDATA_SECTION:4,ENTITY_REFERENCE:5,
ENTITY:6,PROCESSING_INSTRUCTION:7,COMMENT:8,DOCUMENT:9,DOCUMENT_TYPE:10,DOCUMENT_FRAGMENT:11,NOTATION_NODE:12},_addContent:function(a,b,c){if(a instanceof HTML&&-1==a.toString().indexOf("<script")&&""==c.innerHTML){var d=ua.ie();if(!d||d>7&&!DOM.isNode(c,["table","tbody","thead","tfoot","tr","select","fieldset"])){c.innerHTML=a;return}}else if(DOM.isNode(c,DOM.NODE_TYPES.TEXT)){c.data=a;return}var e,c=[],d=[],f=document.createDocumentFragment();a instanceof Array||(a=[a]);for(var g=0;g<a.length;g++)if(e=
a[g],e instanceof HTML){d.push(e.getAction());for(var h=e.getNodes(),k,j=0;j<h.length;j++)k=ua.safari()||ua.ie()&&e.hasOptionElements()?h[j]:h[j].cloneNode(!0),c.push(k),f.appendChild(k)}else is_scalar(e)?(e=document.createTextNode(e),c.push(e),f.appendChild(e)):DOM.isNode(e)&&(c.push(e),f.appendChild(e));b(f);for(g=0;g<d.length;g++)d[g]();return c},getNearest:function(a,b){for(;a&&!DOM.isNode(a,b);)a=a.parentNode;return a},findParentByClass:function(a,b){for(;DOM.isNode(a);){if(CSS.hasClass(a,b))return a;
a=a.parentNode}return null}};window.Event=window.Event||function(){};Event.DATASTORE_KEY="Event.listeners";if(!Event.prototype)Event.prototype={};function $E(a){a=a||window.event||{};if(!a._inherits_from_prototype)for(var b in Event.prototype)try{a[b]=Event.prototype[b]}catch(c){}return a}
(function(){copy_properties(Event.prototype,{_inherits_from_prototype:!0,stop:function(){this.cancelBubble=!0;this.stopPropagation&&this.stopPropagation();return this},prevent:function(){this.returnValue=!1;this.preventDefault&&this.preventDefault();return this},kill:function(){this.stop().prevent();return!1},getTarget:function(){var a=this.target||this.srcElement;return a?basic.$(a):null},getRelatedTarget:function(){var a=this.relatedTarget||this.fromElement;return a?basic.$(a):null},getModifiers:function(){var a=
{control:!!this.ctrlKey,shift:!!this.shiftKey,alt:!!this.altKey,meta:!!this.metaKey};a.access=ua.osx()?a.control:a.alt;a.any=a.control||a.shift||a.alt||a.meta;return a}});copy_properties(Event,{listen:function(a,c,f,j){typeof a=="string"&&(a=basic.$(a,!0));if(typeof j=="undefined")j=Event.Priority.NORMAL;if(typeof c=="object"){var f={},i;for(i in c)f[i]=Event.listen(a,i,c[i],j);return f}if(c.match(/^on/i))throw new TypeError("Bad event name `event': use `click', not `onclick'.");c=c.toLowerCase();
i=DataStore.get(a,b,{});if(d[c])var l=d[c],c=l.base,f=l.wrap(f);e(a,c);a=i[c];j in a||(a[j]=[]);c=new EventHandlerRef(f,a[j],a[j].length);a[j].push(c);return c},fire:function(a,b,c){if(a=DataStore.get(a,Event.DATASTORE_KEY+b))return a($E(c))},stop:function(a){return $E(a).stop()},prevent:function(a){return $E(a).prevent()},kill:function(a){return $E(a).kill()},getKeyCode:function(a){a=$E(a);if(!a)return!1;switch(a.keyCode){case 63232:return 38;case 63233:return 40;case 63234:return 37;case 63235:return 39;
case 63272:case 63273:case 63275:return null;case 63276:return 33;case 63277:return 34}if(a.shiftKey)switch(a.keyCode){case 33:case 34:case 37:case 38:case 39:case 40:return null}return a.keyCode},getPriorities:function(){if(!a){var b=values(Event.Priority);b.sort(function(a,b){return a-b});a=b}return a}});var a=null,b=Event.DATASTORE_KEY,c=function(a){return function(b){if(!DOM.contains(this,b.getRelatedTarget()))return a.call(this,b)}},d={mouseenter:{base:"mouseover",wrap:c},mouseleave:{base:"mouseout",
wrap:c}},e=function(a,c){var d="on"+c,e=f,i=DataStore.get(a,b);c in i||(i[c]={},a.addEventListener?a.addEventListener(c,e,!1):a.attachEvent&&(e=function(){f.call(a,window.event)},a.attachEvent(d,e)),DataStore.set(a,b+c,e),a[d]&&(e=a[d],a[d]=null,Event.listen(a,c,e,Event.Priority.TRADITIONAL)))},f=function(a){var a=$E(a),c=a.type;if(!DataStore.get(this,b))throw Error("Bad listenHandler context.");var d=DataStore.get(this,b)[c];if(!d)throw Error("No registered handlers for `"+c+"'.");for(var c=Event.getPriorities(),
e=0;e<c.length;e++){var f=c[e];if(f in d)for(var f=d[f],l=0;l<f.length;l++)if(f[l])if(f[l].fire(this,a)===!1)return a.kill();else if(a.returnValue===!1)return!1;else if(a.cancelBubble)return a.stop()}}})();Event.Priority={URGENT:-20,TRADITIONAL:-10,NORMAL:0};function EventHandlerRef(a,b,c){this._handler=a;this._container=b;this._index=c}EventHandlerRef.prototype={remove:function(){delete this._handler;delete this._container[this._index]},fire:function(a,b){return this._handler.call(a,b)}};
function URI(a){if(a!==window){if(this===window)return new URI(a||window.location.href);this.parse(a||"")}}
copy_properties(URI,{getRequestURI:function(a,b){return(a===void 0||a)&&window.PageTransitions&&PageTransitions.isInitialized()?PageTransitions.getCurrentURI(!!b).getQualifiedURI():new URI(window.location.href)},getMostRecentURI:function(){return window.PageTransitions&&PageTransitions.isInitialized()?PageTransitions.getMostRecentURI().getQualifiedURI():new URI(window.location.href)},expression:/(((\w+):\/\/)([^\/:]*)(:(\d+))?)?([^#?]*)(\?([^#]*))?(#(.*))?/,arrayQueryExpression:/^(\w+)((?:\[\w*\])+)=?(.*)/,
explodeQuery:function(a){if(!a)return{};for(var b={},a=a.replace(/%5B/ig,"[").replace(/%5D/ig,"]"),a=a.split("&"),c=0,d=a.length;c<d;c++){var e=a[c].match(URI.arrayQueryExpression);if(e){var f=e[2].split(/\]\[|\[|\]/).slice(0,-1),g=e[1],e=URI.decodeComponent(e[3]||"");f[0]=g;for(var g=b,h=0;h<f.length-1;h++)f[h]?(g[f[h]]===void 0&&(g[f[h]]=f[h+1]&&!f[h+1].match(/\d+$/)?{}:[]),g=g[f[h]]):(f[h+1]&&!f[h+1].match(/\d+$/)?g.push({}):g.push([]),g=g[g.length-1]);g instanceof Array&&f[f.length-1]==""?g.push(e):
g[f[f.length-1]]=e}else f=a[c].split("="),b[URI.decodeComponent(f[0])]=f[1]===void 0?null:URI.decodeComponent(f[1])}return b},implodeQuery:function(a,b,c){b=b||"";c===void 0&&(c=!0);var d=[];if(a===null||a===void 0)d.push(c?URI.encodeComponent(b):b);else if(a instanceof Array)for(c=0;c<a.length;++c)try{a[c]!==void 0&&d.push(URI.implodeQuery(a[c],b?b+"["+c+"]":c))}catch(e){}else if(typeof a=="object")if(DOM.isNode(a))d.push("{node}");else for(var f in a)try{a[f]!==void 0&&d.push(URI.implodeQuery(a[f],
b?b+"["+f+"]":f))}catch(g){}else c?d.push(URI.encodeComponent(b)+"="+URI.encodeComponent(a)):d.push(b+"="+a);return d.join("&")},encodeComponent:function(a){for(var a=String(a).split(/([\[\]])/),b=0,c=a.length;b<c;b+=2)a[b]=window.encodeURIComponent(a[b]);return a.join("")},decodeComponent:function(a){return window.decodeURIComponent(a.replace(/\+/g," "))}});
copy_properties(URI.prototype,{parse:function(a){a=a.toString().match(URI.expression);copy_properties(this,{protocol:a[3]||"",domain:a[4]||"",port:a[6]||"",path:a[7]||"",query_s:a[9]||"",fragment:a[11]||""});return this},setProtocol:function(a){this.protocol=a;return this},getProtocol:function(){return this.protocol},setQueryData:function(a){this.query_s=URI.implodeQuery(a);return this},addQueryData:function(a){return this.setQueryData(copy_properties(this.getQueryData(),a))},removeQueryData:function(a){a instanceof
Array||(a=[a]);for(var b=this.getQueryData(),c=0,d=a.length;c<d;++c)delete b[a[c]];return this.setQueryData(b)},getQueryData:function(){return URI.explodeQuery(this.query_s)},setFragment:function(a){this.fragment=a;return this},getFragment:function(){return this.fragment},setDomain:function(a){this.domain=a;return this},getDomain:function(){return this.domain},setPort:function(a){this.port=a;return this},getPort:function(){return this.port},setPath:function(a){this.path=a;return this},getPath:function(){return this.path.replace(/^\/+/,
"/")},toString:function(){var a="";this.protocol&&(a+=this.protocol+"://");this.domain&&(a+=this.domain);this.port&&(a+=":"+this.port);this.domain&&!this.path&&(a+="/");this.path&&(a+=this.path);this.query_s&&(a+="?"+this.query_s);this.fragment&&(a+="#"+this.fragment);return a},valueOf:function(){return this.toString()},isFacebookURI:function(){if(!URI._facebookURIRegex)URI._facebookURIRegex=RegExp("(^|.)facebook.("+env_get("tlds").join("|")+")([^.]*)$","i");return!this.domain||URI._facebookURIRegex.test(this.domain)},
isQuicklingEnabled:function(){return window.Quickling&&Quickling.isActive()&&Quickling.isPageActive(this)},getRegisteredDomain:function(){if(!this.domain)return"";if(!this.isFacebookURI())return null;var a=this.domain.split("."),b=a.indexOf("facebook");return a.slice(b).join(".")},getTld:function(a){if(!this.domain)return"";var b=this.domain.split("."),b=b[b.length-1];if(a)return b;a=env_get("tlds");if(a.indexOf(b)==-1)for(var c=0;c<a.length;++c){var d=a[c];if(RegExp(d+"$").test(this.domain)){b=d;
break}}return b},getUnqualifiedURI:function(){return(new URI(this)).setProtocol(null).setDomain(null).setPort(null)},getQualifiedURI:function(){var a=new URI(this);if(!a.getDomain()){var b=URI();a.setProtocol(b.getProtocol()).setDomain(b.getDomain()).setPort(b.getPort())}return a},isSameOrigin:function(a){a=a||window.location.href;a instanceof URI||new URI(a.toString());return!0},go:function(a){goURI(this,a)},setSubdomain:function(a){var b=(new URI(this)).getQualifiedURI(),c=b.getDomain().split(".");
c.length<=2?c.unshift(a):c[0]=a;return b.setDomain(c.join("."))},getSubdomain:function(){if(!this.getDomain())return"";var a=this.getDomain().split(".");return a.length<=2?"":a[0]}});function Vector2(a,b,c){copy_properties(this,{x:parseFloat(a),y:parseFloat(b),domain:c||"pure"})}
copy_properties(Vector2.prototype,{toString:function(){return"("+this.x+", "+this.y+")"},add:function(a,b){if(arguments.length==1)return a.domain!="pure"&&(a=a.convertTo(this.domain)),this.add(a.x,a.y);var c=parseFloat(a),d=parseFloat(b);return new Vector2(this.x+c,this.y+d,this.domain)},mul:function(a,b){typeof b=="undefined"&&(b=a);return new Vector2(this.x*a,this.y*b,this.domain)},sub:function(a,b){return arguments.length==1?this.add(a.mul(-1)):this.add(-a,-b)},distanceTo:function(a){return this.sub(a).magnitude()},
magnitude:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},convertTo:function(a){if(a!="pure"&&a!="viewport"&&a!="document")return new Vector2(0,0);if(a==this.domain)return new Vector2(this.x,this.y,this.domain);if(a=="pure")return new Vector2(this.x,this.y);if(this.domain=="pure")return new Vector2(0,0);var b=Vector2.getScrollPosition("document"),c=this.x,d=this.y;this.domain=="document"?(c-=b.x,d-=b.y):(c+=b.x,d+=b.y);return new Vector2(c,d,a)},setElementPosition:function(a){var b=this.convertTo("document");
a.style.left=parseInt(b.x)+"px";a.style.top=parseInt(b.y)+"px";return this},setElementDimensions:function(a){return this.setElementWidth(a).setElementHeight(a)},setElementWidth:function(a){a.style.width=parseInt(this.x,10)+"px";return this},setElementHeight:function(a){a.style.height=parseInt(this.y,10)+"px";return this},scrollElementBy:function(a){a==document.body?window.scrollBy(this.x,this.y):(a.scrollLeft+=this.x,a.scrollTop+=this.y);return this}});
copy_properties(Vector2,{compass:{east:"e",west:"w",north:"n",south:"s",center:"center",northeast:"ne",northwest:"nw",southeast:"se",southwest:"sw"},getEventPosition:function(a,b){b=b||"document";a=$E(a);return(new Vector2(a.pageX||a.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),a.pageY||a.clientY+(document.documentElement.scrollTop||document.body.scrollTop),"document")).convertTo(b)},getScrollPosition:function(a){return(new Vector2(document.body.scrollLeft||document.documentElement.scrollLeft,
document.body.scrollTop||document.documentElement.scrollTop,"document")).convertTo(a||"document")},getElementPosition:function(a,b){this.getElementPosition="getBoundingClientRect"in document.documentElement?function(a,b){b=b||"document";if(a){var e=a.getBoundingClientRect(),f=document.documentElement;return(new Vector2(Math.round(e.left)-f.clientLeft,Math.round(e.top)-f.clientTop,"document")).add(Vector2.getScrollPosition("document")).convertTo(b)}}:function(a,b){b=b||"document";if(a){if(ua.safari()<
500&&a.tagName=="TR")a=a.firstChild;for(var e=a.offsetLeft,f=a.offsetTop,g=a.offsetParent,h=!1;a.parentNode&&document.body!=a.parentNode&&document.body!=a.parentNode;){a=a.parentNode;if(!isNaN(a.scrollTop)&&(!(ua.opera()<9.5)||!operaIgnoreScroll[window.getComputedStyle(a,"").getPropertyValue("display")]))f-=a.scrollTop,e-=a.scrollLeft;if(g==a)ua.safari()<500&&a.tagName=="TR"?(f+=a.firstChild.offsetTop,e+=a.firstChild.offsetLeft):(f+=a.offsetTop,e+=a.offsetLeft),g=a.offsetParent;if(g&&CSS.getStyle(g,
"position")=="fixed"){h=!0;f+=g.offsetTop;e+=g.offsetLeft;break}}h&&(g=Vector2.getScrollPosition("document"),e+=g.x,f+=g.y);return(new Vector2(e,f,"document")).convertTo(b)}};return this.getElementPosition(a,b)},getElementDimensions:function(a,b){if(ua.safariPreWebkit()&&a.nodeName=="TR"){var c=a.getElementsByTagName("td");return Vector2.getElementCompassPoint(c[c.length-1],Vector2.compass.southeast,b).sub(Vector2.getElementPosition(c[0],"document",b))}return new Vector2((b?a.clientWidth:a.offsetWidth)||
0,(b?a.clientHeight:a.offsetHeight)||0)},getHiddenElementDimensions:function(a){var b=basic.$(a),a=b.style,c=a.visibility,d=a.position,e=a.display;if(e=="none")a.visibility="hidden",a.position="absolute",a.display="block";b=Vector2.getElementDimensions(b);a.display=e;a.position=d;a.visibility=c;return b},getElementCompassPoint:function(a,b,c){var b=b||Vector2.compass.southeast,d=Vector2.getElementPosition(a),a=Vector2.getElementDimensions(a,c),c=Vector2.compass;switch(b){case c.east:return d.add(a.x,
a.y*0.5);case c.west:return d.add(0,a.y*0.5);case c.north:return d.add(a.x*0.5,0);case c.south:return d.add(a.x*0.5,a.y);case c.center:return d.add(a.mul(0.5));case c.northeast:return d.add(a.x,0);case c.southwest:return d.add(0,a.y);case c.southeast:return d.add(a)}return d},getViewportDimensions:function(){return new Vector2(window&&window.innerWidth||document&&document.documentElement&&document.documentElement.clientWidth||document&&document.body&&document.body.clientWidth||0,window&&window.innerHeight||
document&&document.documentElement&&document.documentElement.clientHeight||document&&document.body&&document.body.clientHeight||0,"viewport")},getDocumentDimensions:function(){return new Vector2(document&&document.documentElement&&document.documentElement.scrollWidth||document&&document.body&&document.body.scrollWidth||0,document&&document.documentElement&&document.documentElement.scrollHeight||document&&document.body&&document.body.scrollHeight||0,"document")},scrollIntoView:function(a){var b=a.offsetParent,
a=Rect(a),c=a.boundWithin(Rect(b)).getPositionVector();a.getPositionVector().sub(c).scrollElementBy(b)}});
var DOMScroll={getScrollState:function(){var a=Vector2.getViewportDimensions(),b=Vector2.getDocumentDimensions(),c=b.x>a.x,a=b.y>a.y;c+=0;a+=0;return new Vector2(c,a)},_scrollbarSize:null,_initScrollbarSize:function(){var a=$N("p");a.style.width="100%";a.style.height="200px";var b=$N("div");b.style.position="absolute";b.style.top="0px";b.style.left="0px";b.style.visibility="hidden";b.style.width="200px";b.style.height="150px";b.style.overflow="hidden";b.appendChild(a);document.body.appendChild(b);
var c=a.offsetWidth;b.style.overflow="scroll";a=a.offsetWidth;if(c==a)a=b.clientWidth;document.body.removeChild(b);DOMScroll._scrollbarSize=c-a;if(DOMScroll._scrollbarSize<5)DOMScroll._scrollbarSize=15},getScrollbarSize:function(){DOMScroll._scrollbarSize===null&&DOMScroll._initScrollbarSize();return DOMScroll._scrollbarSize},scrollTo:function(a,b,c,d){b=b||b===void 0;if(!(a instanceof Vector2)){var e=Vector2.getScrollPosition().x,a=Vector2.getElementPosition(basic.$(a)).y;a-=Math.min(0,Math.max(Vector2.getViewportDimensions().y/
3,100));a=new Vector2(e,a,"document")}c?a.y-=Vector2.getViewportDimensions().y/2:d&&(a.y-=Vector2.getViewportDimensions().y,a.y+=d);a=a.convertTo("document");b&&window.animation?animation(document.body).to("scrollTop",a.y).to("scrollLeft",a.x).ease(animation.ease.end).duration(750).go():window.scrollTo&&window.scrollTo(a.x,a.y)}};
DataStore=window.DataStore||{_storage:{},_elements:{},_tokenCounter:1,_NOT_IN_DOM_CONST:1,_getStorage:function(a){var b;if(a!=null)return typeof a=="string"?b="str_"+a:(b="elem_"+(a.__FB_TOKEN||(a.__FB_TOKEN=[DataStore._tokenCounter++]))[0],DataStore._elements[b]=a),DataStore._storage[b]||(DataStore._storage[b]={})},_shouldDeleteData:function(a){if(!a.nodeName)return!1;try{if(null!=a.offsetParent)return!1}catch(b){}return document.documentElement.contains?!document.documentElement.contains(a):document.documentElement.compareDocumentPosition(a)&
DataStore._NOT_IN_DOM_CONST},set:function(a,b,c){DataStore._getStorage(a)[b]=c;return a},get:function(a,b,c){var d=DataStore._getStorage(a),e=d[b];void 0===e&&typeof a.getAttribute=="function"&&(a=a.getAttribute("data-"+b),e=null===a?void 0:a);c!==void 0&&e===void 0&&(e=d[b]=c);return e},remove:function(a,b){var c=DataStore._getStorage(a),d=c[b];delete c[b];return d},cleanup:function(){var a,b;for(a in DataStore._elements)b=DataStore._elements[a],DataStore._shouldDeleteData(b)&&(delete DataStore._storage[a],
delete DataStore._elements[a])}};function submit_form(a){document.getElementById(a).submit()}function selectallcheck(){document.getElementById("allcheck").checked?jQuery(".itemcheckbox").attr("checked",!0):jQuery(".itemcheckbox").attr("checked",!1)}function isNumber(a){if(isNaN(a.value))a.value=""}
function show_sub_category(a){if(jQuery("#sub_address_"+String(a)).attr("is_request")=="1")jQuery.ajax({type:"POST",beforeSend:function(){jQuery("#sub_address_"+String(a)).html("<div class='loading_progress'><img  src='/css/images/progress.gif'></div>")},url:"/admin.php/category/subcategory",data:"parent_category_id="+a+"&rnd="+Math.random(),dataType:"json",success:function(b){if(b){for(var d=b.length,e="",f=0;f<d;f++){var g=b[f];g&&(e+="<div><span>"+g.category_name+"</span>&nbsp;&nbsp;<span class='dz_pic'><a href=\"javascript:show_sub_category('"+
String(g.id)+"');\">\u67e5\u770b\u5b50\u5730\u5740</a></span>&nbsp;&nbsp;<span class='xg_pic'><a href=\"/admin.php?r=category/add&id="+g.id+"\">\u4fee\u6539</a></span>&nbsp;&nbsp;<span class='sc_pic'><a href=\"javascript:delete_category('"+String(g.id)+"');\">\u5220\u9664</a></span></div>",e+='<div id="sub_address_'+String(g.id)+"\" class='sub_address' is_request='1'>",e+="</div>")}b=document.getElementById("sub_address_"+String(a));b.innerHTML=e;b.style.display="block";jQuery("#sub_address_"+String(a)).attr("is_request",
"2")}}});else{var b=document.getElementById("sub_address_"+String(a));b.style.display=b.style.display=="block"?"none":"block"}}function delete_category(a){document.getElementById("delete_category_id").value=a;document.getElementById("categorydelete-form").submit()}
function show_sub_district(a){if(jQuery("#sub_address_"+String(a)).attr("is_request")=="1")jQuery.ajax({type:"POST",beforeSend:function(){jQuery("#sub_address_"+String(a)).html("<div class='loading_progress'><img  src='/css/images/progress.gif'></div>")},url:"/admin.php/district/subdistrict",data:"parent_district_id="+a+"&rnd="+Math.random(),dataType:"json",success:function(b){if(b){for(var d=b.length,e="",f=0;f<d;f++){var g=b[f];g&&(e+="<div><span>"+g.district_name+"</span>&nbsp;&nbsp;<span class='dz_pic'><a href=\"javascript:show_sub_district('"+
String(g.id)+"');\">\u67e5\u770b\u5b50\u5730\u5740</a></span>&nbsp;&nbsp;<span class='xg_pic'><a href=\"/admin.php?r=district/add&id="+g.id+"\">\u4fee\u6539</a></span>&nbsp;&nbsp;<span class='sc_pic'><a href=\"javascript:delete_district('"+String(g.id)+"');\">\u5220\u9664</a></span></div>",e+='<div id="sub_address_'+String(g.id)+"\" class='sub_address' is_request='1'>",e+="</div>")}b=document.getElementById("sub_address_"+String(a));b.innerHTML=e;b.style.display="block";jQuery("#sub_address_"+String(a)).attr("is_request",
"2")}}});else{var b=document.getElementById("sub_address_"+String(a));b.style.display=b.style.display=="block"?"none":"block"}}function delete_district(a){document.getElementById("delete_district_id").value=a;document.getElementById("districtdelete-form").submit()}
function change_trave_tab(a,b){if(a){for(var c=1;c<=b;c++)jQuery("#menu_tab_desc_"+String(c)).hide(),jQuery("#menu_tab_"+String(c)).removeClass("trave_tab_select");jQuery("#menu_tab_desc_"+String(a)).fadeIn("fast");jQuery("#menu_tab_"+String(a)).addClass("trave_tab_select");jQuery("#menu_tab_0").removeClass("trave_tab_select")}}
function change_limit_tab(a,b){for(var c=1;c<=b;c++)jQuery("#menu_tab_desc_"+String(c)).hide(),jQuery("#menu_tab_"+String(c)).removeClass("limit_tab_select");jQuery("#menu_tab_desc_"+String(a)).fadeIn("fast");jQuery("#menu_tab_"+String(a)).addClass("limit_tab_select")}
function change_tab(a,b){for(var c=1;c<=b;c++)jQuery("#menu_tab_desc_"+String(c)).hide(),jQuery("#menu_tab_"+String(c)).removeClass("tab_select");jQuery("#menu_tab_desc_"+String(a)).fadeIn("fast");jQuery("#menu_tab_"+String(a)).addClass("tab_select")}function show_big_trave_image(a){a=a.getAttribute("big_image");jQuery("#big_trave_image").attr("src",a)}function get_select_value(a){var b="",b=typeof a=="string"?document.getElementById(a):a,a=b.selectedIndex;if(a!=-1)return b.options[a].value}
function select_insurance(a,b){var c=document.getElementById("select_insurance_"+a);get_select_value(c)=="2"?(c=parseInt(adult_nums)+parseInt(child_nums),document.getElementById("insurance_total_price_"+a).innerHTML=b*c,insurance_obj.push({id:a,value:b})):(document.getElementById("insurance_total_price_"+a).innerHTML="0",c=insurance_obj.find_key(a),insurance_obj.remove(c));calculate_total_price()}
function calculate_total_price(){var a=document.getElementById("select_trave_date"),b=a.selectedIndex;b!=-1?(b=a.options[b],a=b.getAttribute("adult_price"),b=b.getAttribute("child_price")):b=a=0;b||(b=a);document.getElementById("hidden_adult_price").value=a;document.getElementById("hidden_child_price").value=b;var c=parseInt(a)*parseInt(adult_nums)+parseInt(b)*parseInt(child_nums);jQuery(".o_price").each(function(){c+=parseInt(jQuery(this).html())});document.getElementById("order_show").innerHTML=
c}function select_f_insurance(a,b){var c=document.getElementById("select_insurance_"+a);get_select_value(c)=="2"?(c=parseInt(adult_nums)+parseInt(child_nums),document.getElementById("insurance_total_price_"+a).innerHTML=b*c,insurance_obj.push({id:a,value:b})):(document.getElementById("insurance_total_price_"+a).innerHTML="0",c=insurance_obj.find_key(a),insurance_obj.remove(c));calculate_f_total_price()}
function calculate_f_total_price(){var a=parseInt(jQuery("#hidden_total_price").val());jQuery(".o_price").each(function(){a+=parseInt(jQuery(this).html())});document.getElementById("order_show").innerHTML=a}
function send_order_info(){if(!document.getElementById("adult_nums").value)return alert("\u6210\u4eba\u6570\u4e0d\u80fd\u4e3a\u7a7a"),!1;if(!get_select_value("select_trave_date"))return alert("\u51fa\u53d1\u65e5\u671f\u4e0d\u80fd\u4e3a\u7a7a"),!1;document.getElementById("hidden_adult_nums").value=document.getElementById("adult_nums").value;document.getElementById("hidden_child_nums").value=document.getElementById("child_nums").value;document.getElementById("hidden_start_date").value=get_select_value("select_trave_date");
document.getElementById("hidden_total_price").value=document.getElementById("order_show").innerHTML;for(var a=insurance_obj.length,b="",c=0;c<a;c++)b?b+=","+insurance_obj[c].id:b=insurance_obj[c].id;document.getElementById("hidden_insurance_ids").value=b;document.getElementById("travelinfo").submit()}
function send_f_order_info(){document.getElementById("hidden_total_price").value=document.getElementById("order_show").innerHTML;for(var a=insurance_obj.length,b="",c=0;c<a;c++)b?b+=","+insurance_obj[c].id:b=insurance_obj[c].id;document.getElementById("hidden_insurance_ids").value=b;document.getElementById("travelfinfo").submit()}function select_trave_date(a){for(var b=document.getElementById("select_trave_date").options,c=b.length,d=0;d<c;d++)if(b[d].value==a)b[d].selected="SELECTED"}
function cope_user_datas(){document.getElementById("user_real_name_1").value=document.getElementById("user_real_name").value;document.getElementById("user_phone_1").value=document.getElementById("user_phone").value}function check_phone(a){is_phone(a,"cell")||alert("\u624b\u673a\u53f7\u7801\u683c\u5f0f\u4e0d\u6b63\u786e")}
function check_telephone(a){var b=document.getElementById("user_area_code").value;b?b&&!is_phone(b+"-"+a,"tele")&&alert("\u56fa\u5b9a\u7535\u8bdd\u683c\u5f0f\u4e0d\u6b63\u786e"):alert("\u8bf7\u9009\u62e9\u533a\u53f7")}function check_email(a){is_email(a)||alert("\u90ae\u7bb1\u683c\u5f0f\u4e0d\u6b63\u786e")}
function is_phone(a,b){switch(b){case "tele":var c=a.match(/^(((\d{3}))|(\d{3}-))?((0\d{2,3})|0\d{2,3}-)?[1-9]\d{6,8}$/);return c?!0:!1;case "cell":var d=a.match(/(?:13\d{1}|1[548][0173689])\d{8}$/);return d?!0:!1;case "tc":var e=a.match(/^1[3,5]\d{9}$/);return e?!0:!1;default:return c=a.match(/^(((\d{3}))|(\d{3}-))?((0\d{2,3})|0\d{2,3}-)?[1-9]\d{6,8}$/),d=a.match(/(?:13\d{1}|1[548][0173689])\d{8}$/),e=a.match(/^1[3,5]\d{9}$/),d||c||e?!0:!1}}
function is_email(a){return a.match(/^([a-z0-9+_]|\-|\.)+@(([a-z0-9_]|\-)+\.)+[a-z]{2,6}$/i)?!0:!1}
var vcity={11:"\u5317\u4eac",12:"\u5929\u6d25",13:"\u6cb3\u5317",14:"\u5c71\u897f",15:"\u5185\u8499\u53e4",21:"\u8fbd\u5b81",22:"\u5409\u6797",23:"\u9ed1\u9f99\u6c5f",31:"\u4e0a\u6d77",32:"\u6c5f\u82cf",33:"\u6d59\u6c5f",34:"\u5b89\u5fbd",35:"\u798f\u5efa",36:"\u6c5f\u897f",37:"\u5c71\u4e1c",41:"\u6cb3\u5357",42:"\u6e56\u5317",43:"\u6e56\u5357",44:"\u5e7f\u4e1c",45:"\u5e7f\u897f",46:"\u6d77\u5357",50:"\u91cd\u5e86",51:"\u56db\u5ddd",52:"\u8d35\u5dde",53:"\u4e91\u5357",54:"\u897f\u85cf",61:"\u9655\u897f",
62:"\u7518\u8083",63:"\u9752\u6d77",64:"\u5b81\u590f",65:"\u65b0\u7586",71:"\u53f0\u6e7e",81:"\u9999\u6e2f",82:"\u6fb3\u95e8",91:"\u56fd\u5916"};function check_cardid(a){return iscardno(a)===!1&&checkprovince(a)===!1&&checkbirthday(a)===!1&&checkparity(a)===!1?(alert("\u60a8\u8f93\u5165\u7684\u8eab\u4efd\u8bc1\u53f7\u7801\u4e0d\u6b63\u786e"),!1):!0}function iscardno(a){return/(^\d{15}$)|(^\d{17}(\d|x)$)/.test(a)===!1?!1:!0}function checkprovince(a){a=a.substr(0,2);return vcity[a]==void 0?!1:!0}
function checkbirthday(a){var b=a.length;if(b=="15"){var c=a.match(/^(\d{6})(\d{2})(\d{2})(\d{2})(\d{3})$/),a=c[2],b=c[3],c=c[4],d=new date("19"+a+"/"+b+"/"+c);return verifybirthday("19"+a,b,c,d)}return b=="18"?(c=a.match(/^(\d{6})(\d{4})(\d{2})(\d{2})(\d{3})([0-9]|x)$/),a=c[2],b=c[3],c=c[4],d=new Date(a+"/"+b+"/"+c),verifybirthday(a,b,c,d)):!1}
function verifybirthday(a,b,c,d){var e=(new Date).getFullYear();return d.getFullYear()==a&&d.getMonth()+1==b&&d.getDate()==c?(a=e-a,a>=3&&a<=100?!0:!1):!1}function checkparity(a){a=changefivteentoeighteen(a);if(a.length=="18"){var b=[7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2],c=0,d;for(d=0;d<17;d++)c+=a.substr(d,1)*b[d];return["1","0","x","9","8","7","6","5","4","3","2"][c%11]==a.substr(17,1)?!0:!1}return!1}
function changefivteentoeighteen(a){if(a.length=="15"){var b=[7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2],c=0,d,a=a.substr(0,6)+"19"+a.substr(6,a.length-6);for(d=0;d<17;d++)c+=a.substr(d,1)*b[d];a+=["1","0","x","9","8","7","6","5","4","3","2"][c%11]}return a}
function remaining_word(a,b,c){var d="",d=typeof a=="string"?document.getElementById(a):a,a=d.value.length;a>=b?document.getElementById(c).innerHTML="<b><font color='#FF0000'>0</font></b>":document.getElementById(c).innerHTML=String(parseInt(b)-parseInt(a))}
function remaining_travelconsulting_word(a,b,c){var d="",d=typeof a=="string"?document.getElementById(a):a,a=d.value.length;a>=b?document.getElementById(c).innerHTML="<b><font color='#FF0000'>0</font></b>":document.getElementById(c).innerHTML=String(parseInt(b)-parseInt(a))}
function show_tip_dialog(a,b){var c=new Dialog;document.getElementById("show_operate_tips_content").innerHTML=b;c.show_dialog(a,{ok_button:{name:"\u786e\u5b9a"},cancel_button:{name:"\u53d6\u6d88"}},{width:300,height:600,HiddenID:"show_operate_tips",overlay:!1,time:"500",auto:!0})}
function upload_user_head(){var a=document.getElementById("userhead-form").cloneNode(!0);a.id="userhead-form_submit";document.getElementById("hidden_iframe").contentWindow.document.getElementById("hidden_userhead-form").appendChild(a);document.getElementById("hidden_iframe").contentWindow.document.getElementById("userhead-form_submit").submit();document.getElementById("show_upload_message").innerHTML="\u6b63\u5728\u5904\u7406\u4e2d....."}
function head_callback(a){document.getElementById("user_head_img").src=a;document.getElementById("user_head_center").src=a;document.getElementById("show_upload_message").innerHTML="\u4fee\u6539\u5934\u50cf\u6210\u529f"}
function subscribe(a){jQuery.ajax({type:"POST",beforeSend:function(){jQuery("#waiting").html("\u6b63\u5728\u5904\u7406\u4e2d...")},url:"/index.php/user/subscribe",data:"s_type="+a+"&rnd="+Math.random(),dataType:"json",success:function(b){a?b.result=="success"&&(jQuery("#cancel_subscribe").show(),jQuery("#ok_subscribe").hide(),jQuery("#email_subscribe_desc").html("\u5df2\u7ecf")):b.result=="success"&&(jQuery("#ok_subscribe").show(),jQuery("#cancel_subscribe").hide(),jQuery("#email_subscribe_desc").html("\u672a"));
jQuery("#waiting").html(b.content)}})}function lock_disabled(a,b){var c="",c=typeof a=="string"?jQuery("#"+a):a;c.val(b);c.attr("disabled",!0)}function unlock_disabled(a,b){var c="",c=typeof a=="string"?jQuery("#"+a):a;c.val(b);c.attr("disabled",!1)}function combine_login_page_params(a){var b="";if(a)for(var c in a)b+="&"+c+"="+a[c];return b}
function submit_consulting(a){var a=jQuery("#"+a).serialize(),b=document.getElementById("consulting_content").value,c=document.getElementById("consulting_email").value;if(!document.getElementById("consulting_verification_code").value)return alert("\u9a8c\u8bc1\u7801\u4e0d\u80fd\u4e3a\u7a7a"),!1;if(c){if(!is_email(c))return alert("\u90ae\u7bb1\u683c\u5f0f\u4e0d\u6b63\u786e"),!1}else return alert("\u90ae\u7bb1\u4e0d\u80fd\u4e3a\u7a7a"),!1;b?b.length>3E3?alert("\u8bc4\u8bba\u5185\u5bb9\u4e0d\u80fd\u5927\u4e8e3000\u4e2a\u5b57"):
(lock_disabled("consulting_buttong","\u54a8\u8be2\u4e2d...."),jQuery.ajax({type:"POST",beforeSend:function(){},url:"/index.php/travel/consulting",processData:!0,data:a+"&rnd="+Math.random(),dataType:"json",success:function(a){a.result=="success"?(jQuery("#trave_consulting_datas").load("index.php?r=travel/consultingdatas",{trave_id:trave_id}),show_tip_dialog("\u54a8\u8be2\u6210\u529f","\u54a8\u8be2\u6210\u529f")):show_tip_dialog("\u54a8\u8be2\u5931\u8d25",a.result);document.getElementById("consulting_verification_code").value=
"";jQuery("#consulting_on_click").click();unlock_disabled("consulting_buttong","\u6211\u8981\u54a8\u8be2")}})):alert("\u8bc4\u8bba\u5185\u5bb9\u4e0d\u80fd\u4e3a\u7a7a")}
function submit_serial_form(a){var a=jQuery("#"+a).serialize(),b=document.getElementById("comment_content").value;if(!document.getElementById("verification_code").value)return alert("\u9a8c\u8bc1\u7801\u4e0d\u80fd\u4e3a\u7a7a"),!1;b?b.length>100?alert("\u8bc4\u8bba\u5185\u5bb9\u4e0d\u80fd\u5927\u4e8e100\u4e2a\u5b57"):(lock_disabled("trave_comment_button","\u53d1\u8868\u8bc4\u8bba\u4e2d...."),jQuery.ajax({type:"POST",beforeSend:function(){},url:"/index.php/travel/travelcomments",processData:!0,data:a+
"&rnd="+Math.random(),dataType:"json",success:function(a){a.result=="success"?(jQuery("#trave_comment_datas").load("index.php?r=travel/commentdatas",{trave_id:trave_id}),show_tip_dialog("\u8bc4\u8bba\u6210\u529f","\u8bc4\u8bba\u6210\u529f")):show_tip_dialog("\u8bc4\u8bba\u5931\u8d25",a.result);document.getElementById("verification_code").value="";jQuery("#comment_on_click").click();jQuery("#comment_on_click").click();unlock_disabled("trave_comment_button","\u53d1\u8868\u8bc4\u8bba")}})):alert("\u8bc4\u8bba\u5185\u5bb9\u4e0d\u80fd\u4e3a\u7a7a")}
function submit_survey_form(a){a=jQuery("#"+a).serialize();jQuery.ajax({type:"POST",beforeSend:function(){},url:"/index.php/site/survey",processData:!0,data:a+"&rnd="+Math.random(),dataType:"json",success:function(a){a.result=="success"?(jQuery("#onlinesurvey_success").fadeIn("fast"),window.setTimeout(function(){jQuery("#onlinesurvey_success").fadeOut("fast")},5E3)):(jQuery("#onlinesurvey_failed").fadeIn("fast"),window.setTimeout(function(){jQuery("#onlinesurvey_failed").fadeOut("fast")},5E3))}})}
var tb_pathToImage="/css/images/loadingAnimation.gif";function Dialog(){this.options=this.button=this.title=""}
Dialog.prototype={set_title:function(a){this.title=a},set_button:function(a){this.button=a},show_dialog:function(a,b,c){this.title=a||"";this.button=b||{};this.options=c||{};this.render_dialog()},render_dialog:function(){if(this.options.overlay){var a="";if(ge("window_wrapper"))a=ge("window_wrapper");else{var a=document.createElement("DIV"),b=navigator.userAgent.toLowerCase();a.className=b.indexOf("mac")!=-1&&b.indexOf("firefox")!=-1?"TB_overlayMacFFBGHack":"window_wrapperBG";a.id="window_wrapper";
var c=this;a.ondblclick=function(){c.hide()}}b=document.createElement("DIV");b.id="TB_load";b.innerHTML='<img src="'+tb_pathToImage+'">';document.body.appendChild(b);document.body.appendChild(a)}else ge("window_wrapper")&&document.body.removeChild(ge("window_wrapper")),b=document.createElement("DIV"),b.id="TB_load",b.innerHTML='<img src="'+tb_pathToImage+'">',document.body.appendChild(b);this.set_init();c=this;window.setTimeout(function(){c.show()},this.options.time?this.options.time:1E3)},set_init:function(){var a=
this.render_content();document.body.appendChild(a);a=ge(this.options.HiddenID);ge("dialog_center").appendChild(a.children[0]);Event.listen(ge("ok_button"),"click",this.click_ok.bind(this));Event.listen(ge("cancel_button"),"click",this.click_cancel.bind(this));Event.listen(ge("dialog_close"),"click",this.click_close.bind(this));this.position()},render_content:function(){var a="";ge("window_content")?(this.options.HiddenID&&ge("dialog_center").children[0]&&ge(this.options.HiddenID).appendChild(ge("dialog_center").children[0]),
a=ge("window_content")):(a=document.createElement("DIV"),a.className="window_content",a.id="window_content");CSS.setStyle(a,"width",String(this.options.width)+"px");CSS.setStyle(a,"height",String(this.options.height)+"px");var b=this.rend_button();a.innerHTML="<table width='100%' cellspacing='0' cellpadding='0'><tbody><tr><td class='left_top'></td><td class='mid_con'></td><td class='right_top'></td></tr><tr><td class='c_mid_con'></td><td class='c_mid_con'><div id='center_content' class='center_content'><div class='center_title' id='center_title'><span class='dialog_title' id='dialog_title'>"+
this.title+"</span><span class='dialog_close' id='dialog_close'>\u5173\u95ed</span></div><div class='dialog_center' id='dialog_center'></div><div class='dialog_button' id='dialog_button'>"+b+"</div></div></td><td class='c_mid_con'></td></tr><tr><td class='left_bottom'></td><td class='mid_con'></td><td class='right_bottom'></td></tr></tbody></table>";return a},rend_button:function(){return"<div class='button_wrapper' id='button_wrapper'><span class='ok_button'><input id='ok_button' type='button'  value='"+
this.button.ok_button.name+"'/></span><span><input id='cancel_button' type='button'  value='"+this.button.cancel_button.name+"'/></span></div>"},click_ok:function(){var a=this.button.ok_button.func;a?eval(a):this.hide()},click_cancel:function(){var a=this.button.cancel_button.func;a?eval(a):this.hide()},click_close:function(){this.hide()},show:function(){ge("TB_load")&&document.body.removeChild(ge("TB_load"));ge("window_wrapper")&&jQuery("#window_wrapper").fadeIn("fast");jQuery("#window_content").fadeIn("fast");
if(this.options.auto){var a=this;window.setTimeout(function(){a.hide()},5E3)}},hide:function(){this.options.HiddenID&&ge("dialog_center").children[0]&&ge(this.options.HiddenID).appendChild(ge("dialog_center").children[0]);ge("window_wrapper")&&jQuery("#window_wrapper").fadeOut("fast");jQuery("#window_content").fadeOut("fast")},position:function(){var a=getPageSize()[0];ua.ie()<=6?CSS.setStyle(ge("window_content"),"left",parseInt((a-this.options.width)/2)+"px"):CSS.setStyle(ge("window_content"),"marginLeft",
parseInt((a-this.options.width)/2)+"px")}};function FrameDialog(){Dialog.call(this)}extend(FrameDialog,Dialog);FrameDialog.prototype.set_init=function(){var a=this.render_content();document.body.appendChild(a);Event.listen(ge("ok_button"),"click",this.click_ok.bind(this));Event.listen(ge("cancel_button"),"click",this.click_cancel.bind(this));Event.listen(ge("dialog_close"),"click",this.click_close.bind(this));this.position()};
FrameDialog.prototype.render_content=function(){var a="";ge("window_content")?a=ge("window_content"):(a=document.createElement("DIV"),a.className="window_content",a.id="window_content");CSS.setStyle(a,"width",String(this.options.width)+"px");CSS.setStyle(a,"height",String(this.options.height)+"px");var b=this.rend_button();a.innerHTML="<table width='100%' cellspacing='0' cellpadding='0'><tbody><tr><td class='left_top'></td><td class='mid_con'></td><td class='right_top'></td></tr><tr><td class='c_mid_con'></td><td class='c_mid_con'><div id='center_content' class='center_content'><div class='center_title' id='center_title'><span class='dialog_title' id='dialog_title'>"+
this.title+"</span><span class='dialog_close' id='dialog_close'>\u5173\u95ed</span></div><div class='dialog_center' id='dialog_center'><iframe frameborder='0' class='dialog_iframe' style='width:"+(this.options.width-60)+"px;height:"+this.options.height+"px;' src='"+this.options.FrameUrl+"'></iframe></div><div class='dialog_button' id='dialog_button'>"+b+"</div></div></td><td class='c_mid_con'></td></tr><tr><td class='left_bottom'></td><td class='mid_con'></td><td class='right_bottom'></td></tr></tbody></table>";
return a};FrameDialog.prototype.hide=function(){ge("window_wrapper")&&jQuery("#window_wrapper").fadeOut("fast");jQuery("#window_content").fadeOut("fast")};var Extend=function(a,b){for(var c in b)a[c]=b[c];return a},Calendar=Class.create();
Calendar.prototype={initialize:function(a,b){this.Container=document.getElementById(a);this.Days=[];this.SetOptions(b);this.trave_date_datas=this.options.trave_date_datas||"";this.Year=this.options.Year||(new Date).getFullYear();this.Month=this.options.Month||(new Date).getMonth()+1;this.SelectDay=this.options.SelectDay?new Date(this.options.SelectDay):null;this.onSelectDay=this.options.onSelectDay;this.onToday=this.options.onToday;this.onFinish=this.options.onFinish;this.Draw()},SetOptions:function(a){this.options=
{Year:0,Month:0,trave_date_datas:null,SelectDay:null,onSelectDay:function(){},onToday:function(){},onFinish:function(){}};Extend(this.options,a||{})},NowMonth:function(){this.PreDraw(new Date)},PreMonth:function(){this.PreDraw(new Date(this.Year,this.Month-2,1))},NextMonth:function(){this.PreDraw(new Date(this.Year,this.Month,1))},PreYear:function(){this.PreDraw(new Date(this.Year-1,this.Month-1,1))},NextYear:function(){this.PreDraw(new Date(this.Year+1,this.Month-1,1))},PreDraw:function(a){this.Year=
a.getFullYear();this.Month=a.getMonth()+1;this.Draw()},Draw:function(){for(var a=[],b=1,c=(new Date(this.Year,this.Month-1,1)).getDay();b<=c;b++)a.push(0);b=1;for(c=(new Date(this.Year,this.Month,0)).getDate();b<=c;b++)a.push(b);this.Days=[];for(c=document.createDocumentFragment();a.length;){for(var d=document.createElement("tr"),b=1;b<=7;b++){var e=document.createElement("td");e.innerHTML="&nbsp;";if(a.length){var f=a.shift();if(f){var g=new Date(this.Year,this.Month-1,f);e.innerHTML=this.contact_d(f);
this.Days[f]=e;this.IsSame(g,new Date)&&this.onToday(e);this.SelectDay&&this.IsSame(g,this.SelectDay)&&this.onSelectDay(e)}}d.appendChild(e)}c.appendChild(d)}for(;this.Container.hasChildNodes();)this.Container.removeChild(this.Container.firstChild);this.Container.appendChild(c);this.onFinish()},contact_d:function(a){for(var b=this.Year+"/"+this.Month+"/"+(a<=9?"0"+String(a):String(a)),c=this.trave_date_datas,d=c.length,e=0;e<d;e++)c[e].trave_date==b?this.Year>=(new Date).getFullYear()?this.Year==
(new Date).getFullYear()?this.Month==(new Date).getMonth()+1?a>=(new Date).getDate()?a+="<div class='calendar_trave_date' id='t_"+c[e].trave_date+"'><a href=\"javascript:select_trave_date('"+c[e].trave_date+"')\">\uffe5"+c[e].trave_price+"\u8d77</a></div><div class='trave_seats'>"+c[e].seats+"</div>":a="<div class='text_999999'>"+a+"<div class='calendar_trave_date'>\uffe5"+c[e].trave_price+"\u8d77</div><div class='trave_seats'>"+c[e].seats+"</div></div>":this.Month<(new Date).getMonth()+1?a="<div class='text_999999'>"+
a+"<div class='calendar_trave_date'>\uffe5"+c[e].trave_price+"\u8d77</div><div class='trave_seats'>"+c[e].seats+"</div></div>":a+="<div class='calendar_trave_date' id='t_"+c[e].trave_date+"'><a href=\"javascript:select_trave_date('"+c[e].trave_date+"')\">\uffe5"+c[e].trave_price+"\u8d77</a></div><div class='trave_seats'>"+c[e].seats+"</div>":a+="<div class='calendar_trave_date' id='t_"+c[e].trave_date+"'><a href=\"javascript:select_trave_date('"+c[e].trave_date+"')\">\uffe5"+c[e].trave_price+"\u8d77</a></div><div class='trave_seats'>"+
c[e].seats+"</div>":a="<div class='text_999999'>"+a+"<div class='calendar_trave_date'>\uffe5"+c[e].trave_price+"\u8d77</div><div class='trave_seats'>"+c[e].seats+"</div></div>":this.Year>=(new Date).getFullYear()?this.Year==(new Date).getFullYear()&&(this.Month==(new Date).getMonth()+1?a<(new Date).getDate()&&(a="<div class='text_999999'>"+a+"</div>"):this.Month<(new Date).getMonth()+1&&(a="<div class='text_999999'>"+a+"</div>")):a="<div class='text_999999'>"+a+"</div>";return a},IsSame:function(a,
b){return a.getFullYear()==b.getFullYear()&&a.getMonth()==b.getMonth()&&a.getDate()==b.getDate()}};
function get_phone_verification(a){var b=jQuery("#"+a).val();b?is_phone(b,"")?jQuery.ajax({type:"POST",beforeSend:function(){jQuery("#user_phone_tip").html("<div class='loading_progress'><img  src='/css/images/progress.gif'></div>")},url:"/index.php/site/phoneverification",data:"user_phone="+jQuery("#"+a).val()+"&rnd="+Math.random(),success:function(a){jQuery("#user_phone_tip").html(a);jQuery("#hidden_user_phone").val(b)}}):jQuery("#user_phone_tip").html("\u624b\u673a\u53f7\u7801\u683c\u5f0f\u4e0d\u6b63\u786e"):
jQuery("#user_phone_tip").html("\u624b\u673a\u53f7\u7801\u4e0d\u80fd\u4e3a\u7a7a")};
